import type { Metadata } from "next";
import { helvetica, helveticaRounded, helveticaCompressed } from "@/lib/fonts";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${helvetica.variable} ${helveticaRounded.variable} ${helveticaCompressed.variable} antialiased`}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
