import type { Metadata } from "next";
import { lotaGrotesque, lotaGrotesqueAlt1, lotaGrotesqueAlt2, lotaGrotesqueAlt3 } from "@/lib/fonts";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";
import SmoothScrolling from "@/components/SmoothScrolling";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${lotaGrotesque.variable} ${lotaGrotesqueAlt1.variable} ${lotaGrotesqueAlt2.variable} ${lotaGrotesqueAlt3.variable} antialiased`}
      >
        <CustomCursor />
        {/* Smooth scrolling provider - wraps all content for kinetic scrolling */}
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
